version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
    - 9003:9000
    - 9002:9001
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
    - minio-data:/data

  redis:
    image: redis:7.0.11-alpine
    ports:
    - 6381:6380

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uspos
    ports:
      - "5433:5432"

  api:
    build: .
    # command: python manage.py runserver
    command: [ "make", "start-api" ]

    ports:
      - "8000:8000"

    depends_on:
      - db
      - minio

    env_file:
      - .env

    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: uspos
      DB_HOST: db
      DB_PORT: 5433

volumes:
  minio-data:
