version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
    - 9000:9000
    - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
    - minio-data:/data

  redis:
    image: redis:7.0.11-alpine
    ports:
    - 6381:6380

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uspos
    ports:
      - "5433:5432"

  api:
    build: .
    command: [ "make", "start-api" ]

    ports:
      - "8000:8000"

    depends_on:
      - db
      - minio

    env_file:
      - ./env/.env

  worker1:
    container_name: worker1
    build: .
    command: [ "make", "run-celery-worker" ]

    depends_on:
      - redis
      - api

    env_file:
      - ./env/.env

volumes:
  minio-data:
