version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
    - 9000:9000
    - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
    - minio-data:/data

volumes:
  minio-data: