# Generated by Django 5.1.1 on 2024-09-07 06:54

import django.db.models.deletion
import src.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=src.core.models.Image.upload_image_to)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.bread')),
            ],
        ),
    ]
