# Generated by Django 5.1.1 on 2024-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_bread_adaptability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bread",
            name="origin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
