# Generated by Django 5.1.1 on 2024-09-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_bread_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bread",
            name="bred_for",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bread",
            name="breed_group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bread",
            name="life_span",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bread",
            name="temperament",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
