# Generated by Django 5.1.1 on 2024-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_bread_bred_for_alter_bread_breed_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bread",
            name="external_id",
            field=models.IntegerField(),
        ),
    ]
